services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: portalfirma
      MYSQL_USER: portal
      MYSQL_PASSWORD: portal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - portal_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes:
  portal_mysql_data:
